steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - --trigger-http
      - --runtime=python37
      - --region=europe-west1
      - turnio_websearch_context
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - --trigger-http
      - --runtime=python37
      - --region=europe-west1
      - turnio_websearch_webhook
